[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/rustylynch/go-rpmutils"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  version = "0.5.4"

[prune]
  go-tests = true
  unused-packages = true
